{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config-cli" (include "watkins.keycloak.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  BASE_URL: {{ include "watkins.url" . | b64enc | quote }}
  API_BASE_URL: {{ include "watkins.api.url" . | b64enc | quote }}
  KEYCLOAK_REALM: {{ .Values.keycloakConfig.realm | b64enc | quote }}
  BITBUCKET_ENABLED: {{ printf "%t" (or (not .Values.gitProviders.bitbucket.clientId) (not .Values.gitProviders.bitbucket.clientSecret) | not ) | b64enc | quote }}
  BITBUCKET_CLIENT_ID: {{ .Values.gitProviders.bitbucket.clientId | b64enc | quote }}
  BITBUCKET_CLIENT_SECRET: {{ .Values.gitProviders.bitbucket.clientSecret | b64enc | quote }}
  BITBUCKET_SERVER_ENABLED: {{ printf "%t" (or (not .Values.gitProviders.bitbucketServer.clientId) (not .Values.gitProviders.bitbucketServer.clientSecret) | not ) | b64enc | quote }}
  BITBUCKET_SERVER_CLIENT_ID: {{ .Values.gitProviders.bitbucketServer.clientId | b64enc | quote }}
  BITBUCKET_SERVER_CLIENT_SECRET: {{ .Values.gitProviders.bitbucketServer.clientSecret | b64enc | quote }}
  BITBUCKET_SERVER_BASE_URL: {{ .Values.gitProviders.bitbucketServer.clientId | b64enc | quote }}
  GITHUB_ENABLED: {{ printf "%t" (or (not .Values.gitProviders.github.clientId) (not .Values.gitProviders.github.clientSecret) | not ) | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.gitProviders.github.clientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.gitProviders.github.clientSecret | b64enc | quote }}
  GITHUB_ENTERPRISE_SERVER_ENABLED: {{ printf "%t" (or (not .Values.gitProviders.githubEnterpriseServer.clientId) (not .Values.gitProviders.githubEnterpriseServer.clientSecret) | not ) | b64enc | quote }}
  GITHUB_ENTERPRISE_SERVER_CLIENT_ID: {{ .Values.gitProviders.githubEnterpriseServer.clientId | b64enc | quote }}
  GITHUB_ENTERPRISE_SERVER_CLIENT_SECRET: {{ .Values.gitProviders.githubEnterpriseServer.clientSecret | b64enc | quote }}
  GITHUB_ENTERPRISE_SERVER_BASE_URL: {{ .Values.gitProviders.githubEnterpriseServer.baseUrl | b64enc | quote }}
  GITHUB_ENTERPRISE_SERVER_API_URL: {{ .Values.gitProviders.githubEnterpriseServer.apiUrl | b64enc | quote }}
  GITLAB_ENABLED: {{ printf "%t" (or (not .Values.gitProviders.gitlab.clientId) (not .Values.gitProviders.gitlab.clientSecret) | not ) | b64enc | quote }}
  GITLAB_CLIENT_ID: {{ .Values.gitProviders.gitlab.clientId | b64enc | quote }}
  GITLAB_CLIENT_SECRET: {{ .Values.gitProviders.gitlab.clientSecret | b64enc | quote }}
  GITLAB_SELF_MANAGED_ENABLED: {{ printf "%t" (or (not .Values.gitProviders.gitlabSelfManaged.clientId) (not .Values.gitProviders.gitlabSelfManaged.clientSecret) | not ) | b64enc | quote }}
  GITLAB_SELF_MANAGED_CLIENT_ID: {{ .Values.gitProviders.gitlabSelfManaged.clientId | b64enc | quote }}
  GITLAB_SELF_MANAGED_CLIENT_SECRET: {{ .Values.gitProviders.gitlabSelfManaged.clientSecret | b64enc | quote }}
  GITLAB_SELF_MANAGED_BASE_URL: {{ .Values.gitProviders.gitlabSelfManaged.baseUrl | b64enc | quote }}
  API_CLIENT_SECRET: {{ .Values.keycloakConfig.clients.api.clientSecret | b64enc | quote }}
  WORKSPACE_PROXY_CLIENT_SECRET: {{ .Values.keycloakConfig.clients.workspaceProxy.clientSecret | b64enc | quote }}
{{- end }}
