{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config-cli" (include "watkins.keycloak.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ADMIN_DASHBOARD_URL: {{ include "watkins.adminDashboard.url" . | b64enc | quote }}
  BASE_URL: {{ include "watkins.url" . | b64enc | quote }}
  API_BASE_URL: {{ include "watkins.api.url" . | b64enc | quote }}
  KEYCLOAK_REALM: {{ .Values.keycloakConfig.realm | b64enc | quote }}
  API_CLIENT_SECRET: {{ .Values.keycloakConfig.clients.api.clientSecret | b64enc | quote }}
  WORKSPACE_PROXY_CLIENT_SECRET: {{ .Values.keycloakConfig.clients.workspaceProxy.clientSecret | b64enc | quote }}
{{- end }}
