{{- $adminPassword := include "common.secrets.passwords.manage" (dict "secret" (printf "%s" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-") "key" "admin-password" "length" 10 "providedValues" (list "configuration.auth.adminPassword") "failOnNew" false "skipB64enc" true "skipQuote" true "context" $) -}}
{{- if not $adminPassword -}}
{{- $adminPassword = randAlphaNum 10 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: secret
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-password: {{ $adminPassword | b64enc | quote }}
  api-client-secret: {{ .Values.keycloakConfig.clients.api.clientSecret | b64enc | quote }}
  workspace-proxy-client-secret: {{ .Values.keycloakConfig.clients.workspaceProxy.clientSecret | b64enc | quote }}
  encryption-secret: {{ .Values.configuration.encryptionSecret | b64enc | quote }}
  workspace-proxy-session-secret: {{ .Values.configuration.sessionSecret | b64enc | quote }}
  workspace-proxy-cookie-secret: {{ .Values.configuration.cookieSecret | b64enc | quote }}
