apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: secret
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  api-client-secret: {{ .Values.keycloakConfig.clients.api.clientSecret | b64enc }}
  workspace-proxy-client-secret: {{ .Values.keycloakConfig.clients.workspaceProxy.clientSecret | b64enc }}
  encryption-secret: {{ .Values.configuration.encryptionSecret | b64enc }}
  workspace-proxy-session-secret: {{ .Values.configuration.sessionSecret | b64enc }}
  workspace-proxy-cookie-secret: {{ .Values.configuration.cookieSecret | b64enc }}
