{{- $host_cert := genSelfSignedCertWithKey "" (list) (list) 4096 (genPrivateKey "rsa") }}
{{- $host_key := $host_cert.Key | b64enc }}
{{- $host_crt := $host_cert.Cert | b64enc }}
{{- $host_secret := (lookup "v1" "Secret" .Release.Namespace (include "watkins.sshGateway.fullname" .)) }}
{{- if $host_secret }}
{{- $host_key = index $host_secret.data "ssh_host_key" }}
{{- $host_crt = index $host_secret.data "ssh_host_crt" }}
{{- end }}
{{- $ws_cert := genSelfSignedCertWithKey "" (list) (list) 4096 (genPrivateKey "rsa") }}
{{- $ws_key := $ws_cert.Key | b64enc }}
{{- $ws_crt := $ws_cert.Cert | b64enc }}
{{- $ws_secret := (lookup "v1" "Secret" .Release.Namespace (include "watkins.sshGateway.fullname" .)) }}
{{- if $ws_secret }}
{{- $ws_key = index $ws_secret.data "workspace_key" }}
{{- $ws_crt = index $ws_secret.data "workspace_crt" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "watkins.sshGateway.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ssh-gateway
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ssh_host_crt: {{ $host_crt }}
  ssh_host_key: {{ $host_key }}
  workspace_crt: {{ $ws_crt }}
  workspace_key: {{ $ws_key }}