apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "watkins.workspaceProvisioner.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- if .Values.components.workspaceProvisioner.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.components.workspaceProvisioner.serviceAccount.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "watkins.workspaceProvisioner.fullname" . }}
  {{- with .Values.components.workspaceProvisioner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
