apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "watkins.workspaceInstance.serviceAccountName" . }}
  namespace: {{ include "watkins.workspaceNamespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "watkins.workspaceInstance.serviceAccountName" . }}
{{- include "watkins.imagePullSecrets" . }}
