{{- if .Values.components.workspaceVolumeInit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "watkins.workspaceVolumeInit.fullname" . }}
  namespace: {{ include "watkins.workspaceNamespace" . }}
  labels:
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    component: workspace-volume-init
{{ include "watkins.imagePullSecrets" . }}
{{- end }}
