apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "daytona.namespace" . }}
  name: {{ include "daytona.fullname" . }}-jaeger
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
spec:
  replicas: {{ .Values.services.jaeger.replicaCount }}
  selector:
    matchLabels:
      {{- include "daytona.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: jaeger
  template:
    metadata:
      {{- with .Values.services.jaeger.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "daytona.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: jaeger
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "daytona.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: jaeger
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: jaegertracing/all-in-one:1.67.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 4318
              protocol: TCP
          resources:
            {{- toYaml .Values.services.jaeger.resources | nindent 12 }}
      {{- with .Values.services.jaeger.nodeSelector | default .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.jaeger.affinity | default .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.jaeger.tolerations | default .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
