apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daytona.secretName" . }}
  namespace: "{{ include "daytona.namespace" . }}"
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc }}
  {{- if .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc }}
  {{- end }}
