apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daytona.secretName" . }}
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ .Values.database.password }}
  {{- if .Values.redis.password }}
  redis-password: {{ .Values.redis.password }}
  {{- end }}
---
{{- if (index .Values.services "ssh-gateway").enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daytona.secretName" . }}-ssh
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
type: Opaque
data:
  SSH_PRIVATE_KEY: {{ (index .Values.services "ssh-gateway").sshKeys.privClientSSHKey | trim | b64enc }}
  SSH_PRIVATE_PUB_KEY: {{ (index .Values.services "ssh-gateway").sshKeys.pubClientSSHKey | trim | b64enc }}
  SSH_HOST_KEY: {{ (index .Values.services "ssh-gateway").sshKeys.privGatewaySSHKey | trim | b64enc }}
  API_KEY: {{ (index .Values.services "ssh-gateway").apiKey | b64enc }}
{{- end }}
