{{- if .Values.services.sshGateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daytona.secretName" . }}-ssh
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
type: Opaque
data:
  SSH_PRIVATE_KEY: {{ .Values.services.sshGateway.sshKeys.privClientSSHKey | trim | b64enc }}
  SSH_PRIVATE_PUB_KEY: {{ .Values.services.sshGateway.sshKeys.pubClientSSHKey | trim | b64enc }}
  SSH_HOST_KEY: {{ .Values.services.sshGateway.sshKeys.privGatewaySSHKey | trim | b64enc }}
  API_KEY: {{ .Values.services.sshGateway.apiKey | b64enc }}
{{- end }}
