{{- if .Values.services.sshGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "daytona.fullname" . }}-ssh-gateway
  namespace: {{ include "daytona.namespace" . }}
  labels:
    {{- include "daytona.labels" . | nindent 4 }}
    app.kubernetes.io/component: ssh-gateway
  {{- with .Values.services.sshGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.sshGateway.service.type }}
  ports:
    - port: {{ .Values.services.sshGateway.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "daytona.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ssh-gateway
{{- end }}
