name: Publish Charts

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'README.md'
  #     - 'charts/**/README.md'
  #     - 'LICENSE'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          helm_version: 3.14.4
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          charts_url: https://charts.daytona.io
          branch: releases
          target_dir: charts
          index_dir: .
